# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bta2Vpx9mQpzb-PoFBUKB50Viiqv-08H
"""

import streamlit as st
import joblib

!pip install streamlit
import streamlit as st
import joblib

# Load saved model and vectorizer
model = joblib.load('sentiment_model.pkl')
vectorizer = joblib.load('vectorizer.pkl')

# Streamlit App
st.title('Sentiment Analysis App')
st.write("Enter a movie review below to get the predicted sentiment.")

# User Imput
user_input = st.text_area("Enter Movie Review:")

# Predict Button
if st.button("Analyze Sentiment"):
    if user_input.strip() == "":
        st.warning("Please enter a review.")
    else:
        input_vector = vectorizer.transform([user_input])
        result = model.predict(input_vector)[0]
        sentiment = "😊 Positive" if result == 1 else "😠 Negative"
        st.subheader("Predicted Sentiment:")
        st.write(sentiment)
